/**
 * LETARGIA CHARACTER CREAT - API Error Codes and Factory
 */

export const API_VERSION = "1.0.0";

export const ErrorCodes = {
  NO_PERMISSION: "NO_PERMISSION",
  NOT_OWNER: "NOT_OWNER",
  NOT_GM: "NOT_GM",
  INVALID_COMPOSITION: "INVALID_COMPOSITION",
  INVALID_PACK: "INVALID_PACK",
  INVALID_PIECE: "INVALID_PIECE",
  INVALID_MANIFEST: "INVALID_MANIFEST",
  INVALID_PACK_ID: "INVALID_PACK_ID",
  PACK_EXISTS: "PACK_EXISTS",
  PACK_NOT_FOUND: "PACK_NOT_FOUND",
  DUPLICATE_PIECE_ID: "DUPLICATE_PIECE_ID",
  API_VERSION_MISMATCH: "API_VERSION_MISMATCH",
  INVALID_PATH: "INVALID_PATH",
  ACTOR_NOT_FOUND: "ACTOR_NOT_FOUND",
  TOKEN_NOT_FOUND: "TOKEN_NOT_FOUND",
  NO_APPLICABLE_ACTORS: "NO_APPLICABLE_ACTORS",
  CONCURRENT_MODIFICATION: "CONCURRENT_MODIFICATION",
  EXPORT_FAILED: "EXPORT_FAILED",
  UPLOAD_FAILED: "UPLOAD_FAILED",
  DOWNLOAD_FAILED: "DOWNLOAD_FAILED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  NOT_INITIALIZED: "NOT_INITIALIZED"
};

export function createError(code, message, data = {}) {
  const err = new Error(message);
  err.code = code;
  err.module = "letargia-character-creat";
  err.data = data;
  return err;
}